id = "prisma"
name = "Prisma"
description = "Prisma support."
version = "0.1.5"
schema_version = 1
authors = ["Matthew Gramigna <matthewgramigna@gmail.com>", "Victor Quiroz <git@victorhqc.com>"]
repository = "https://github.com/zed-extensions/prisma"

[language_servers.prisma-language-server]
name = "Prisma Language Server"
language = "Prisma"

[grammars.prisma]
repository = "https://github.com/victorhqc/tree-sitter-prisma"
commit = "3556b2c1f20ec9ac91e92d32c43d9d2a0ca3cc49"
